<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>onboardsdk</name>
  <version>4.1.0</version>
  <description>DJI Onboard SDK (OSDK) 4.1.0</description>
  <maintainer email="afewgoodman.choi@gmail.com">bchoi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>libusb</depend>
  <depend>ffmpeg</depend>
  <depend>libudev</depend>
  <depend>opencv</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
